version: '3.7'
services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
  celery-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "source conga-env/bin/activate && celery -A app.celery worker --loglevel=INFO"
  redis:
    image: redis:6-buster
    ports:
      - 6379:6379
  database:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=simulator
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  selenium-server:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
  allure-server:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
  ui-tests:
    build:
      context: ./
      dockerfile: uitests.Dockerfile
    volumes:
      - ./allure-results:/usr/src/app/allure-results
      - ./allure-reports:/usr/src/app/default-reports
    command: bash -c "/usr/wait-for-it.sh frontend:8080 && /usr/wait-for-it.sh server:5000 && /usr/wait-for-it.sh selenium-server:4444 && behave -f allure_behave.formatter:AllureFormatter -o ./allure-results"


volumes:
  database-data: