version: '3.7'
services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000