version: '3.7'
services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
  celery-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A app.celery worker --loglevel=INFO
  redis:
    image: redis:6-buster
    ports:
      - 6379:6379
  database:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=simulator
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  database-data: